<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <EnableHarmony>true</EnableHarmony>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="i18n/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/*.bak" />
    <None Remove="**/*.bak" />
    <Compile Remove="**/*.txt" />
    <None Remove="**/*.txt" />
    <None Remove="CommonlyReferencedCode/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.ReSharper.CommandLineTools" Version="2025.2.5" PrivateAssets="All" />
  </ItemGroup>
</Project>